version: '3.4'

services:
  sourcingdb:
    image: mongo
    
  rabbitmq:
    image: rabbitmq:3.8.14-management
    
  sourcingsqldb:
    image: mcr.microsoft.com/mssql/server

  onlineauctionapp.productapi:
    image: ${DOCKER_REGISTRY-}onlineauctionappproductapi
    build:
      context: .
      dockerfile: src/Services/Products/OnlineAuctionApp.ProductAPI/Dockerfile

  onlineauctionapp.auctionapi:
    image: ${DOCKER_REGISTRY-}onlineauctionappauctionapi
    build:
      context: .
      dockerfile: src/Services/Auctions/OnlineAuctionApp.AuctionAPI/Dockerfile

